name = "proxg"
main = "_worker.js"
compatibility_date = "2026-08-20"
compatibility_flags = [ "nodejs_compat" ]

# ✅ ဒီ line ကို ထည့်ပါ
keep_vars = true

[vars]
#UUID = ""
WS_PATH = "galaxy-tunnel"
PROXYIP = "cdn-b100.xn--b6gac.eu.org"
PROXY_LIST_URL = "https://raw.githubusercontent.com/gprox-galaxy/Cloudflare-Galaxytunnel/refs/heads/main/PROXYIP.txt"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
